config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'profiles/show'
  get 'profiles/edit'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  root 'static_pages#top'
  get 'static_pages/top', to: 'static_pages#top'

  get '/login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  namespace :admin do
    root 'dashboards#index'
    get '/login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[show edit update index destroy]
    resources :boards, only: %i[show edit update index destroy]
  end

  resources :users, only: %i[new create index]

  resource :profiles, only: %i[show edit update]

  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'bookmarks'
    end
  end
  resources :bookmarks, only: %i[create destroy]

  resources :password_resets, only: %i[create new edit update]

  get '*path', controller: 'application', action: 'render_404'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  mount_uploader :board_image, BoardImageUploader
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_boards, through: :bookmarks, source: :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :body, presence: true, length: { maximum: 65_535 }
end

app/controllers/admin/boards_controller.rb
class Admin::BoardsController < Admin::BaseController
  before_action :set_board, only: %i[edit destroy update show]
  def index
    @q = Board.ransack(params[:q])
    @boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def show; end

  def update
    if @board.update(board_params)
      redirect_to admin_board_path(@board), success: t('.success', item: Board.model_name.human)
    else
      render :edit
      flash.now[:danger] = t('.fail', item: Board.model_name.human)
    end
  end

  def destroy
    @board.destroy!
    redirect_to admin_boards_path, success: t('.success', item: Board.model_name.human)
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :body, :board_image, :board_image_cache)
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: %i[edit destroy update]
  before_action :require_login
  def index
    @q = Board.ransack(params[:q])
    @boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def new
    @board = Board.new
  end

  def edit; end

  def bookmarks
    @q = current_user.bookmark_boards.ransack(params[:q])
    @bookmark_boards = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def show
    @board = Board.find(params[:id])
    @comment = Comment.new
    @comments = @board.comments.includes(:user).order(created_at: :desc)
  end

  def create
    @board = current_user.boards.new(board_params)
    if @board.save
      redirect_to boards_path, success: t('.success', item: Board.model_name.human)
    else
      render new_board_path
      flash.now[:danger] = t('.fail', item: Board.model_name.human)
    end
  end

  def update
    if @board.update(board_params)
      redirect_to @board, success: t('.success', item: Board.model_name.human)
    else
      render :edit
      flash.now[:danger] = t('.fail', item: Board.model_name.human)
    end
  end

  def destroy
    @board.destroy!
    redirect_to boards_path, success: t('.success', item: Board.model_name.human)
  end

  private

  def set_board
    @board = current_user.boards.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:title, :body, :board_image, :board_image_cache)
  end
end

app/views/admin/boards/_board.html.erb
<tr>
  <td>
    <%= board.id %>
  </td>
  <td>
    <%= board.title %>
  </td>
  <td>
    <%= board.user.decorate.full_name %>
  </td>
  <td>
    <%= l board.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admin_board_path(board), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_board_path(board), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_board_path(board), method: :delete, data: { confirm: t('admin.defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/boards/_form.html.erb
<%= form_with model: board, url: admin_board_path(board), local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: "form-control" %>          
  </div>
  <div class="form-group">
  <%= f.label :body %>
  <%= f.text_area :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :board_image %>
    <%= f.file_field :board_image, onchange: 'previewImage()', class: 'form-control' %>
    <%= f.hidden_field :board_image_cache %>
    </div>
    <div class='mt-3 mb-3'>
    <%= image_tag board.board_image.url, id: 'preview', size: '300x200' %>
  </div>
  <%= f.submit class: "btn btn-primary", rows: 10 %>
<% end %>

app/views/admin/boards/_search_form.html.erb
<%= search_form_for @q, url: admin_boards_path do |f| %>
  <div class="row">
    <div class="form-inline align-items-center mx-auto">
      <div class="col-auto">
        <%= f.search_field :title_or_body_cont, class: 'form-control', placeholder: t('admin.defaults.search_word') %>
      </div>
      <div class="col-auto">
        <%= f.date_field :created_at_gteq, class: 'form-control' %> 
        <span> ~ </span>
        <%= f.date_field :created_at_lteq_end_of_day, class: 'form-control' %> 
      </div>
      <div class="col-auto">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/boards/edit.html.erb
<% content_for(:title, @board.title) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
        <h1><%= t('.title') %></h1>
            <%= render 'form',{ board: @board } %>
    </div>
  </div>
</div>

app/views/admin/boards/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_form'%>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= Board.human_attribute_name(:id) %></th>
          <th scope="col"><%= Board.human_attribute_name(:title) %></th>
          <th scope="col"><%= Board.human_attribute_name(:user) %></th>
          <th scope="col"><%= Board.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @boards %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <!-- ページネーション -->
      <%= paginate @boards %>
    </div>
  </div>
</div>

app/views/admin/boards/show.html.erb
<% content_for(:title, @board.title) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= @board.title %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admin_board_path(@board), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admin_board_path(@board), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:id) %></th>
          <td><%= @board.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:title) %></th>
          <td><%= @board.title %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:user) %></th>
          <td><%= @board.user.decorate.full_name %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:body) %></th>
          <td><%= @board.body %></td>
        </tr>
        <tr>
          <th scope="row"><%= Board.human_attribute_name(:created_at) %></th>
          <td><%= l @board.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>