config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  get 'profiles/show'
  get 'profiles/edit'
  get 'bookmarks/create'
  get 'bookmarks/destroy'
  root 'static_pages#top'
  get 'static_pages/top', to: 'static_pages#top'

  get '/login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'

  namespace :admin do
    root 'dashboards#index'
    get '/login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :users, only: %i[show edit update index destroy]
    resources :boards, only: %i[show edit update index destroy]
  end

  resources :users, only: %i[new create index]

  resource :profiles, only: %i[show edit update]

  resources :boards do
    resources :comments, only: %i[create destroy], shallow: true
    collection do
      get 'bookmarks'
    end
  end
  resources :bookmarks, only: %i[create destroy]

  resources :password_resets, only: %i[create new edit update]

  get '*path', controller: 'application', action: 'render_404'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/shared/_footer.html.erb
<footer class="main-footer">
  <strong>Copyright &copy; 2019 RUNTEQ.</strong>
  All rights reserved.
</footer>

app/views/admin/shared/_header.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
    </li>
  </ul>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
      <%= link_to t('defaults.logout'), admin_logout_path, class: 'nav-link', method: :delete %>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/admin/shared/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <%= image_tag 'AdminLTELogo.png', class: 'brand-image img-circle elevation-3' %>
    <span class="brand-text font-weight-light">AdminLTE 3</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <%= image_tag current_user.avatar_url, class: 'img-circle elevation-2' %>
      </div>
      <div class="info">
        <a href="#" class="d-block"><%= current_user.decorate.full_name %></a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <li class="nav-item">
          <%= link_to admin_boards_path, class: "nav-link #{active_if('admin/boards')}" do %>
            <i class="nav-icon far fa-file"></i>
            <p>
              <%= t('admin.boards.index.title') %>
            </p>
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to admin_users_path, class: "nav-link #{active_if('admin/users')}" do %>
            <i class="nav-icon far fa-user"></i>
            <p>
              <%= t('admin.users.index.title') %>
            </p>
          <% end %>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>